### ISSUE TITLE
[Q] Install to eMMC

### ISSUE THREAD

**Issue by PulsarFX** [inindev/nanopi-r5#1]
I've read the readme so far and I am wondering how to install to the integrated emmc instead of sd card.
Would this be an option during this step?
> when the micro sd has finished imaging, eject and use it to boot the nanopi r5c or r5s to finish setup

Thanks for providing a plain debian and your support!

**Comment by JesterGeek** [comment]
I successfully installed the provided img on my NanoPi R5C's eMMC in MaskRom mode by using rkdeveloptool. No SD card involved.

`rkdeveloptool db MiniLoaderAll.bin`
`rkdeveloptool wl 0x0 nanopi-r5-bookworm-rc3.img`

I got MiniLoaderAll.bin from FriendlyELEC's [download link](https://download.friendlyelec.com/NanoPiR5C) (03_Partition image files/friendlywrt22-images.tgz).

**Comment by inindev** [comment]
Create an MMC card and boot using it it.  You may need to have the mask button down to bypass booting from the internal eMMC.  Once booted from the removable MMC, you will see the internal eMMC as /dev/mmcblk1.  Wget the binary and xzcat it to /dev/mmcblk1:

wget https://github.com/inindev/nanopi-r5/releases/download/v12-rc3/nanopi-r5_bookworm-rc3.img.xz
sudo su
xzcat nanopi-r5_bookworm-rc3.img.xz > /dev/mmcblk1

Then reboot.
