### ISSUE TITLE
IPv6 is not working after installation

### ISSUE THREAD

**Issue by laf0rge** [inindev/nanopi-r5#15]
First of all, thanks for your work - it is much appreciated.

I've been trying to wrap my head around why on earth IPv6 is not working like it normally does on all Debian systems.  It turns out the kernel cmdline is using `ipv6.disable=1`.  

I didn't find any statement on why this is done, nor that it is done, or how to remove it.

**Comment by laf0rge** [comment]
looks like one can edit `/boot/boot.txt` to remove the ipv6.disable and then run tthe script `/boot/mkscr.sh` to fix this.  The question remains why it is done in the first place.

**Comment by inindev** [comment]
You are right, it should default on as is the norm with Debian.  I will publish the next rev with it enabled by default.

**Comment by jflasch2** [comment]
Great thread , fixed my system now too. 

BTW Thanks so much for your work .

**Comment by inindev** [comment]
v12.0.3 resolves this issue: https://github.com/inindev/nanopi-r5/releases/tag/v12.0.3

Anyone wanting to disable ipv6 can edit the top of ```/boot/mk_extlinux``` to include ```ipv6.disable=1```
```
EXTL_MENU_ENABLE='auto'      # true, false, auto
EXTL_MENU_ITEMS=2            # max kernels in menu
EXTL_MENU_TIMEOUT=3          # timeout in seconds
EXLT_CMD_LINE='ro rootwait ipv6.disable=1'
```

Then re-run ```/boot/mk_extlinux``` which will update the ```/boot/extlinux/extlinux.conf``` file.
