### ISSUE TITLE
Use the 1203 DTB to boot the armbian system and the R5C network port status indicator does not blink

### ISSUE THREAD

**Issue by kongjun0** [inindev/nanopi-r5#19]
Can you provide ideas?
![QQ截图20230821160355](https://github.com/inindev/nanopi-r5/assets/33769434/2ffdcb7d-ffac-4d81-af38-f23ae75e079f)
![image](https://github.com/inindev/nanopi-r5/assets/33769434/9f2c6eb7-f22e-45eb-8963-689583460b05)
use cat led-lan*/linux,default-trigger
invalid

**Comment by inindev** [comment]
Re you saying there was a .dtb version that did work at one point?

https://github.com/inindev/nanopi-r5/releases/download/v12.0.3/rk3568-nanopi-r5c.dtb
https://github.com/inindev/nanopi-r5/releases/download/v12.0.2/rk3568-nanopi-r5c.dtb
https://github.com/inindev/nanopi-r5/releases/download/v12.0.1/rk3568-nanopi-r5c.dtb
https://github.com/inindev/nanopi-r5/releases/download/v12.0/rk3568-nanopi-r5c.dtb

I do not run Armbian so I do not have first-hand experience with it. Is there an advantage running Armbian over Debian for the R5S?

**Comment by inindev** [comment]
There was a similar discussion yesterday with Red Hat Linux and @arbv was able to figure it out.  This thread may be of use to you: https://github.com/inindev/nanopi-r5/issues/18

**Comment by arbv** [comment]
@inindev Just a clarification: not Red Hat, but NixOS. Though, it is hardly disco specific.

@kongjun0 The point is that the right DTB file was not loaded and passed to the kernel.

**Comment by kongjun0** [comment]
> @inindev Just a clarification: not Red Hat, but NixOS. Though, it is hardly distro specific.
> 
> @kongjun0 The point is that the right DTB file was not loaded and passed to the kernel.

Is there a solution to this problem?

**Comment by arbv** [comment]
@kongjun0 Go read the thread: https://github.com/inindev/nanopi-r5/issues/18
Everything you need is there towards the end of the thread. The DTB file for your device is available in the download section of the project.

**Comment by inindev** [comment]
Is there still an open question on this issue or should it be closed?
