### ISSUE TITLE
Ethernet ports do not work correctly on 2.5GB switch

### ISSUE THREAD

**Issue by twinclouds** [inindev/nanopi-r5#24]
This implementation of Debian for NanoPi R5C is much better than the stock images.  However, when I test the ethernet behavior, I found it works well on Gigabit ethernet switches but not on 2.5G switches.  On 2.5G switched network, it always negotiate to 100MB date rate, even though on 1GB switches it achieves 1Gb throughput.  From lshw, it appears the NIC installed in the R5C are RTL8125, but the driver used is r8169.  I don't know if this is the problem or not, though.  Below is the lshw output:

NanoPi-R5C:~$ sudo lshw -C network
  *-network
       description: Ethernet interface
       product: RTL8125 2.5GbE Controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0001:01:00.0
       logical name: lan0
       version: 05
       serial: a8:be:fc:be:a0:e8
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix vpd bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=6.1.0-10-arm64 firmware=rtl8125b-2_0.0.2 07/13/20 ip=192.168.2.110 latency=0 link=no multicast=yes port=twisted pair
       resources: irq:41 ioport:100000(size=256) memory:f2200000-f220ffff memory:f2210000-f2213fff

**Comment by inindev** [comment]
great detective work, thank you

can you try installing the realtek firmare to see if the correct driver gets loaded?

```apt install firmware-realtek```

**Comment by inindev** [comment]
I am seeing the same behavior here:
```
       description: Ethernet interface
       product: RTL8125 2.5GbE Controller
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: lan1
       version: 05
       serial: 74:04:fd:0f:ec:a4
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix vpd bus_master cap_list ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=r8169 driverversion=6.1.0-13-arm64 duplex=full firmware=rtl8125b-2_0.0.2 07/13/20 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
       resources: irq:40 ioport:1000(size=256) memory:f4200000-f420ffff memory:f4210000-f4213fff
```

**Comment by twinclouds** [comment]
I tried "apt install firmware-realtek" that John suggested and it works.  I think my issue can be closed.
