### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Tchoupinax** [inindev/nanopi-r5#28]
Hello @inindev,

I want just to share you how much grateful I am to your work on this repository. I tested a lot of things on the last days (DietPi, ARMbian, all internet and reddit forums) to find the best way to use my NanoPI R5S with a new NVMe. I tested like dozens of setup, from scratch install and images. I found an opened issue on DietPi talking about the fact this hardware isn't able to boot directly to NVMe and so it needs a bootloader to do the job. Your section `booting from internal NVMe (r5s only)` answers to it PERFECTLY and it the easiest task to do I have seen this week.

Your tutorial and your work are quick, crystal clear and useful!
Thank for your share, I love the open source initiative for this.

Again, thanks!

**Comment by inindev** [comment]
Thank you for your feedback, that is nice to hear!
