### ISSUE TITLE
ETA on Kernel 6.7

### ISSUE THREAD

**Issue by mrbluecoat** [inindev/nanopi-r5#30]
Thank you so much for this project - so awesome to have kernel 6.1 on the R5C!

Any ETA on updating to kernel 6.7? https://github.com/debian-kernel/linux/releases

(or at least 6.6.23? https://www.armbian.com/nanopi-r5c/ )

**Comment by inindev** [comment]
That archive is not official:
_Debian Kernel
Unofficial archlinux kernel for debian_

My goal here is to run real up-stream Debian ARM64 Linux, so all updates come from the natural ```apt update && apt upgrade``` upstream Debian repositories.  Currently it is 6.1.0-18: https://packages.debian.org/bookworm/kernel/linux-image-arm64

If you want to run the Debian testing (trixie) kernel, it is at 6.6.15: https://packages.debian.org/testing/kernel/linux-image-arm64

```
wget http://ftp.us.debian.org/debian/pool/main/l/linux-signed-arm64/linux-image-arm64_6.6.15-2_arm64.deb
sudo dpkg -i linux-image-arm64_6.6.15-2_arm64.deb
```
It wont update automatically however, and I have not tested this combination myself.
