### ISSUE TITLE
kconfig options

### ISSUE THREAD

**Issue by ibrtuyima** [inindev/nanopi-r5#8]
Good job so far, your built image is working great but I am wondering if it's possible to add the ability to update kconfig options in your build scripts. 

Thank you

**Comment by inindev** [comment]
The kernel is whatever comes from the debian mothership -- everything but the device tree is just stock.  It is my own preference to run stock Debian and/or Fedora as I believe they are the fastest to address and patch CVE security issues: https://www.debian.org/security/cve-compatibility

The kernel command line parameters can be edited in ```/boot/boot.txt``` then compiled into ```boot.scr``` by running ```./mkscr.sh``` located in the ```/boot``` directory.

Debian makes it very easy to build custom kernels by using the config located in ```/boot/config-6.1.0-9-arm64```.  see: https://www.debian.org/doc/manuals/debian-kernel-handbook/ch-common-tasks.html#s-common-official

(you may know all of this already, but I post it for anyone else reading this who may not)
